### ISSUE TITLE
About train classification (2nd) model

### ISSUE THREAD

**Issue by WangRongsheng** [KazuhideMimura/yolov5-ichthyolith#1]
Hello，I have two questions：
（1）How do I organize my data in order to train a classification model？
（2）For classification model，Why is it not `Resnet` or other model, but `yolov5s`？

**Comment by KazuhideMimura** [comment]
Hi, thank you for question.

(1) classifier.py uses pytorch's image loader (LL 74-77)
https://pytorch.org/vision/main/generated/torchvision.datasets.ImageFolder.html

dataset folder should be following hierarchies

(dataset name)
> train
> > (cls1)
> > > (image001.jpg)
> > > (image002.jpg)
> > > ...
> > 
> > (cls2)
> > > (image003.jpg)
> > > (image004.jpg)
> > > ...
> > 
> 
> test
> > (cls1)
> > > (image005.jpg)
> > > (image006.jpg)
> > > ...
> > 
> > (cls2)
> > > (image007.jpg)
> > > (image008.jpg)
> > > ...

you can use any image name or folder name, except for "train" and "test"

(2) I don't have particular reason for yolov5s. I'm also trying efficientnet. 
In ultralytics/yolov5, it seems that yolo & efficientnet models are available, although I'm not sure Resnet model can be used.
https://github.com/ultralytics/yolov5/blob/classifier/classifier.py (LL88-107)

**Comment by WangRongsheng** [comment]
Thank you for doing such a good job. I will continue to pay attention to it！
